accounts/urls.py
from django.urls import path, include
from .views import login_view, logout_view,\
    register_view,  password_reset_request


app_name = 'accounts'
urlpatterns = [

    path('accounts/login', login_view, name='login'),
    path('accounts/logout', logout_view, name='logout'),
    path('accounts/register', register_view, name='register'),
    path('accounts/password_reset_request', password_reset_request, name='password_reset'),
]

core/urls.py
from django.urls import path
from .views import IndexClass, About, Contact

app_name = 'core'
urlpatterns = [
    
    path('', IndexClass.as_view(), name='homepage'),
    path('core/about', About.as_view(), name='about'),
    path('core/contact', Contact.as_view(), name='contact'),
]

course_store/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from .admin import admin_site

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('', include('api_rest.urls')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Cấu hình hiển thị images

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')                        # cleaned_data.get làm hợp lệ dữ liệu
        password = self.cleaned_data.get('password')

        if username and password:                                           # nếu có nhập dữ liệu user và pass
            user = authenticate(username=username, password=password)       # chứng thực dữ liệu
            if not user:                                                    # Nếu ko có user
                raise forms.ValidationError('User not database')            # Báo user ko có trong db
            if not user.check_password(password):                           # kiêm tra pass
                raise forms.ValidationError('Password not true')
            if not user.is_active:                                          # kiểm tra user active chưa
                raise forms.ValidationError('User not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)            # goi super trả về UserLoginForm và báo dữ liệu đã hợp lệ


class UserRegisterForm(forms.ModelForm):

    email = forms.EmailField(label='InsertEmail')
    password = forms.CharField(widget=forms.PasswordInput, label='Insert Pass')
    re_password = forms.CharField(widget=forms.PasswordInput, label='Re Insert Pass')

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 're_password']

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')  # cleaned_data.get làm hợp lệ dữ liệu
        password = self.cleaned_data.get('password')
        re_password = self.cleaned_data.get('re_password')

        if password != re_password:
            raise forms.ValidationError('Password not true')
        emailQ = User.objects.filter(email=email)
        if emailQ.exists():                                 # Kiểm tra email có trong db ko
            raise forms.ValidationError('Email used')

        return super(UserRegisterForm, self).clean(*args, **kwargs)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from products.models import Category
from .forms import UserLoginForm, UserRegisterForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, Http404 

# *********************Register***************************

from django.contrib.auth.forms import PasswordResetForm             # import form làm register
from django.contrib.auth.models import User                         # lấy tb user làm register
from django.utils.http import urlsafe_base64_encode                 # mã hóa làm register
from django.utils.encoding import force_bytes                       # mã hóa làm register
from django.contrib.auth.tokens import default_token_generator      # mã hóa làm register
from django.template.loader import render_to_string                 # render nội dung làm register
from django.db.models.query_utils import Q                          # lọc email làm register
from django.core.mail import send_mail, BadHeaderError              # làm register

# Create your views here.

def login_view(request):
    
    category = Category.objects.all()
    form = UserLoginForm(request.POST or None)

    if form.is_valid():                                     # nếu form hợp lệ
        username = form.cleaned_data.get('username')        # lấy username từ from
        password = form.cleaned_data.get('password')        # lấy password  từ form
        user = authenticate(username=username, password=password)           # chứng thực dữ liệu

        login(request, user)                                # gọi thư viện login
       
        return redirect('/')

    return render(request, 'accounts/login.html', {'category': category, 'formKeys': form,})


def logout_view(request):
    logout(request)
    return redirect('/')

def register_view(request):

    category = Category.objects.all()
    if request.method == 'POST':                    # Nếu yêu cầu là Post
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():                                     # nếu form hợp lệ
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')        # lấy password  từ form
            user.set_password(password)
            user.save()

            new_user = authenticate(username=user.username, password=password)
            login(request, new_user)                            # gọi thư viện login

            return redirect('/')
    form = UserRegisterForm() 
    return render(request, 'accounts/register.html', {'category': category, 'formKey': form,})


def password_reset_request(request):
    
    category = Category.objects.all()
    if request.method == 'POST':                    # Nếu yêu cầu là Post
        form = PasswordResetForm(request.POST)      # tạo đối tượng cho form
        if form.is_valid():
            data = form.cleaned_data['email']       # lấy địa chỉ mail
            associate_user = User.objects.filter(Q(email=data))    # lấy email của form
            for user in associate_user:
                subject = 'Password reset request'
                emailTemplateName = 'accounts/email/password_reset_request.txt'
                
                # Soạn nội dung đầu mail
                compose = {
                    "email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
					'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                }
                email = render_to_string(emailTemplateName, compose)
                
                try:
                    send_mail(subject, email, 'lkienminh@gmail.com' , [user.email], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Invalid')
                return redirect('/')
            
    form = PasswordResetForm()                      # Ngược lại tạo form request bình thường
    return render(request, 'accounts/password_reset_request.html', {'category': category, 'formKeys': form})
    
def password_reset_done(request):
    return render(request, 'accounts/password_reset_done.html', {})


def password_reset_confirm(request):
    return render(request, 'accounts/password_reset_confirm.html', {})


def password_reset_complete(request):
    return render(request, 'accounts/password_reset_complete.html', {})

templates/accounts/login.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

{% if user.is_authenticated %}
  Đã login rồi
{% else %}

<style>

  .btn-color{
  background-color: #0e1c36;
  color: #fff;

}

.profile-image-pic{
  height: 200px;
  width: 200px;
  object-fit: cover;
}

.cardbody-color{
  background-color: #ebf2fa;
}

a{
  text-decoration: none;
}
</style>
<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class="text-center text-dark mt-5">Login Form</h2>
        <div class="text-center mb-5 text-dark">Made with bootstrap</div>
        <div class="card my-5">

          <form class="card-body cardbody-color p-lg-5" method="post">
            {% csrf_token %}
            <div class="text-center">
              <img src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
                width="200px" alt="profile">
            </div>

            <div class="mb-3">
              <label for="id_username">Username</label>
              <input type="text" class="form-control" name="username" required id="id_username" placeholder="User Name">

            </div>
            <div class="mb-3">
              <label for="id_password">Password</label>
              <input type="password" class="form-control" name="password" required id="id_password" placeholder="password">
            </div>
            <div class="text-center"><button type="submit" class="btn btn-color px-5 mb-5 w-100">Login</button></div>
            <div id="emailHelp" class="form-text text-center mb-5 text-dark">Not
              Registered? <a href="#" class="text-dark fw-bold"> Create an
                Account</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'core/base.html' %}

{% block content %} 
  
  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %} 

{% block content %}

   
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'core/base.html' %}

{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

templates/accounts/password_reset_request.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_authenticated %}
  
	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ formKeys|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset Password</button>
        </form>
  	</div>
	  
{% else %}
Vui lòng login or register  	  
{% endif %} 
{% endblock %}

templates/accounts/register.html
{% extends 'core/base.html' %}

{% block content %}

{% if user.is_authenticated %}
  Đã Register rồi
{% else %}

<style>img {width:50%;}</style>
<section class="testimonial py-5" id="testimonial">
    <div class="container">
        <div class="row ">
            <div class="col-md-4 py-5 bg-primary text-white text-center ">
                <div class=" ">
                    <div class="card-body">
                        <img src="http://www.ansonika.com/mavia/img/registration_bg.svg" style="width:30%">
                        <h2 class="py-3">Registration</h2>
                        <p>Tation argumentum et usu, dicit viderer evertitur te has. Eu dictas concludaturque usu, facete detracto patrioque an per, lucilius pertinacia eu vel.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-8 py-5 border">
                <h4 class="pb-4">Please fill with your details</h4>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <input name="username" required id="id_username" placeholder="User name" class="form-control" type="text">
                        </div> <br />
                        <div class="form-group col-md-6">
                          <input name="email" required id="id_email" class="form-control" placeholder="InsertEmail" type="email">
                        </div>
                      </div>
                    <br />
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input id="id_password" name="password" placeholder="Insert Password" class="form-control" required type="password">
                        </div> <br />
                        <div class="form-group col-md-6">
                            <input id="id_re_password" name="re_password" placeholder="Re_Password" class="form-control" required type="password">
                        </div>
                        <br />
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-sm btn-primary">Register</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% comment %} <form method="post">
    {% csrf_token %}
    {{ formKey }}
    <button type="submit" class="btn btn-sm btn-danger">Đăng ký</button>
</form> {% endcomment %}
{% endif %}
{% endblock %}