core/urls.py
from django.urls import path
from .views import IndexClass, About, Contact

app_name = 'core'
urlpatterns = [
    
    path('', IndexClass.as_view(), name='homepage'),
    path('core/about', About.as_view(), name='about'),
    path('core/contact', Contact.as_view(), name='contact'),
]

course_store/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from .admin import admin_site

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('', include('api_rest.urls')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Cấu hình hiển thị images

products/urls.py
from django.urls import path
from .views import detail, detaillesson, typevideo, typecourse

app_name = 'products'
urlpatterns = [
    
    path('detail/<int:courses_id>', detail, name='detail'),
    path('detaillesson/<int:lesson_id>/<int:lessoncourse_id>', detaillesson, name='detaillesson'),
    path('products/typevideo/<int:category_id>', typevideo, name='typevideo'),
    path('products/typecourse/<int:type_id>', typecourse, name='typecourse'),
]

products/models.py
from django.db import models
from ckeditor.fields import RichTextField
from embed_video.fields import EmbedVideoField
from autoslug import AutoSlugField
from datetime import date

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255, null=False, unique=True)
    decription = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=255, null=False, unique=True)
    active = models.BooleanField(default=True) 
    
    def __str__(self):
        return self.title

class Itembase(models.Model):
    class Meta:
        abstract = True                                # class chung và class Meta ko cho tạo tb nữa
        
    subject = models.CharField(max_length=100, null=False)
    image = models.ImageField(upload_to='itembase/%Y/%m/%d', default=None)
    created_date = models.DateTimeField(auto_now_add=True) 
    update_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    link_video = models.CharField(max_length=300)
    type = models.IntegerField(default=True)
    slug = models.SlugField(unique=True, max_length=255, blank=True, null=True)
    
    def __str__(selt):
        return selt.subject
     
class Course(Itembase):
    class Meta:
        unique_together = ('subject', 'category')   # danh mục ko được phép trùng tên khóa học
        ordering = ["-id"]                          # order by id desc  
        
    
    description = RichTextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)    #  khi xoá thì trường này sẽ là null ko bị xoá theo
    # category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT)          #  bài học mặc định
    star = models.FloatField(default=0)
    inventory  = models.IntegerField(default=0)
    

class Variation(models.Model):
    
    title = models.CharField(max_length=255, null=False, unique=True)
    product = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    price = models.IntegerField(default=500000)
    sale_price = models.IntegerField(default=0, blank=True, null=True)
    discount_price = models.IntegerField(default=0, blank=True, null=True)
    discount_percentage = models.IntegerField(default=0, blank=True, null=True)
    discount_from_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    discount_to_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    active = models.BooleanField(default=True)
    
    def calculator(seft):
        if((seft.discount_from_date >= date.today()) and (seft.discount_to_date <= date.today())):
            
            if seft.discount_percentage != None:
                return  (seft.price * ((1-seft.discount_percentage/100))/1000, 0) * 1000
            
            # if seft.discount_price != None:
            #     return  (seft.price * ((1-seft.discount_percentage/100))/1000, 0) * 1000
    
class Lesson(Itembase):
    class Meta:
        unique_together = ('subject', 'course')   # khóa học  ko được phép trùng tên bài học
        ordering = ["-id"]                        # order by id desc      
    content = RichTextField(null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)    #  Xoá theo
    # course = models.ForeignKey(Course, on_delete=models.PROTECT)  #  Ko được phép xoá
    tags = models.ManyToManyField('Tag', blank=True, null=True)      # class Tag nằm dưới nên phải để trong dấu nhấy, nếu nằm trên thì ko cần

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = AutoSlugField(populate_from='name', max_length=255, null=False, unique=True)
    
    def __str__(selt):
        return selt.name
    
class ImageCourseLess(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='itembase/%Y/%m/%d', default=None)
    
class VideoCourseLess(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, blank=True, null=True)
    video = EmbedVideoField()

products/views.py
from django.shortcuts import render
from products.models import Category, Course, Lesson, Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404 

# *********************Class based view***************************
from django.views.generic import ListView, DetailView, View


# Create your views here.

def detail(request, courses_id):

    category = Category.objects.all()
    try:
        lesson = Lesson.objects.filter(course=courses_id)
        courses_id = Course.objects.get(id=courses_id)
    except Course.DoesNotExist:
        raise Http404("Question does not exist")
    
    return render(request, 'products/detail.html', {'lesson': lesson,
                                                    'courses_id': courses_id,
                                                    'category': category,})

def detaillesson(request, lesson_id, lessoncourse_id):

    category = Category.objects.all()
    try:
        lessonid = Lesson.objects.get(id=lesson_id)
        lessonfil = Lesson.objects.filter(course_id=lessoncourse_id)
    except Course.DoesNotExist:
        raise Http404("Question does not exist")
    
    return render(request, 'products/detail_lesson.html', {'lessonid': lessonid,
                                                           'lessonfil': lessonfil,
                                                           'category': category,})


def typevideo(request, category_id):
    
    category = Category.objects.all()
    coursesFilId = Course.objects.filter(category_id=category_id)

    page = request.GET.get('page', 1)
    paginator = Paginator(coursesFilId, 6)
    try:
        coursesFilId = paginator.page(page)
    except PageNotAnInteger:
        coursesFilId = paginator.page(1)
    except EmptyPage:
        coursesFilId = paginator.page(paginator.num_pages)  # Trang cuối

    return render(request, 'products/typevideo.html', {'category': category,
                                                       'coursesFilId': coursesFilId,})

def typecourse(request, type_id):
    
    category = Category.objects.all()
    coursesFilId = Course.objects.filter(type=type_id)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(coursesFilId, 6)
    try:
        coursesFilId = paginator.page(page)
    except PageNotAnInteger:
        coursesFilId = paginator.page(1)
    except EmptyPage:
        coursesFilId = paginator.page(paginator.num_pages)  # Trang cuối
    
    return render(request, 'products/typecourse.html', {'category': category,
                                                       'coursesFilId': coursesFilId})

templates/products/detail.html
{% extends 'core/base.html' %}
{% load embed_video_tags %}
{% load static %}


{% block content %}
  <div class="container py-4">
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Category</h2>
          <p class="text-center">{% video courses_id.link_video 'small' %}</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h3> {{ courses_id.subject }}</h3>
          <p>{{ courses_id.description | safe }}</p>
            {% for lessons in lesson %}
            <p><a href="{% url 'products:detaillesson' lessons.id lessons.course_id %}">{{ lessons.subject }}</a></p>
            {% endfor %}
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <br><hr><br>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/products/detail_lesson.html
{% extends 'core/base.html' %}
{% load embed_video_tags %}
{% load static %}


{% block content %}
  <div class="container py-4">
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <p class="text-center">{% video lessonid.link_video 'small' %}</p>
          <p>{{ lessonid.subject  }}</p>
          <p>{{ lessonid.content | safe }}</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
              {% for lessonfils in lessonfil %}
                <p><a href="{% url 'products:detaillesson' lessonfils.id lessonfils.course_id %}">{{ lessonfils.subject }}</a></p>
              {% endfor %}
        </div>
      </div>
    </div>

    <br><hr><br>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/products/typecourse.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for coursesFilIds in coursesFilId %}
              <div class="col">
                  <div class="card shadow-sm">
                      <img src="{{ coursesFilIds.image.url }}" alt="{{ coursesFilIds.subject }}" height="225px" />
                      <div class="card-body">
                          <p class="text-center">
                              {% if user.is_authenticated or coursesFilIds.type == 0 %}
                                  <a href="{% url 'products:detail' coursesFilIds.id %}">
                                      {{coursesFilIds.subject }}
                                  </a>
                              {% else %}
                                  {{coursesFilIds.subject }}
                              {% endif %}
                          </p>
                          <p class="card-text">{{coursesFilIds.description | safe }}</p>
                          <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                  {% if user.is_authenticated or coursesFilIds.type == 0 %}
                                  <a href="{% url 'products:detail' coursesFilIds.id %}" role="button"\
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                  {% else %}
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Get account</button>
                                  <!-- Modal -->
                                  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                          </div>
                                          <div class="modal-body">
                                              Please login view video
                                          </div>
                                          <div class="modal-footer">
                                          <a href="accounts/login" role="button" class="btn btn-primary">I see</a>
                                          </div>
                                      </div>
                                      </div>
                                  </div>
                                  {% endif %}
                              </div>
                              <small class="text-muted">Star: {{coursesFilIds.star }}</small>
                          </div>
                      </div>
                      <div class="text-center"><strong>{{coursesFilIds.category }}</strong></div>
                  </div>
              </div>  
          {% endfor %}
    </div>
    <br><hr>
    <!-- This is paginator-->
    <div class="text-end">
      {% if coursesFilId.has_previous %}
          <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page=1">Trang đầu</a>
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.previous_page_number }}">Trang trước</a>-->
      {% endif %}

      {% for i in coursesFilId.paginator.page_range %}
        {% if coursesFilId.number == i %}
          <a class="btn btn-sm btn-outline-primary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
        {% elif i > coursesFilId.number|add:'-10' and i < coursesFilId.number|add:'10' %}
          <a class="btn btn-sm btn-outline-secondary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
        {% endif %}
      {% endfor %}

      {% if coursesFilId.has_next %}
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.next_page_number }}">Tiếp theo</a>-->
          <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesFilId.paginator.num_pages }}">Trang cuối</a>
      {% endif %}
  </div>
  </div>
</div>
{% endblock %}

templates/products/typevideo.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for coursesFilIds in coursesFilId %}
              <div class="col">
                  <div class="card shadow-sm">
                      <img src="{{ coursesFilIds.image.url }}" alt="{{ coursesFilIds.subject }}" height="225px" />
                      <div class="card-body">
                          <p class="text-center">
                              {% if user.is_authenticated or coursesFilIds.type == 0 %}
                                  <a href="{% url 'products:detail' coursesFilIds.id %}">
                                      {{coursesFilIds.subject }}
                                  </a>
                              {% else %}
                                  {{coursesFilIds.subject }}
                              {% endif %}
                          </p>
                          <p class="card-text">{{coursesFilIds.description | safe }}</p>
                          <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                  {% if user.is_authenticated or coursesFilIds.type == 0 %}
                                  <a href="{% url 'products:detail' coursesFilIds.id %}" role="button"\
                                   class="btn btn-sm btn-outline-secondary">View</a>
                                  {% else %}
                                  <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Get account</button>
                                  <!-- Modal -->
                                  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="modal-header">
                                          <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                          </div>
                                          <div class="modal-body">
                                              Please login view video
                                          </div>
                                          <div class="modal-footer">
                                          <a href="accounts/login" role="button" class="btn btn-primary">I see</a>
                                          </div>
                                      </div>
                                      </div>
                                  </div>
                                  {% endif %}
                              </div>
                              <small class="text-muted">Star: {{coursesFilIds.star }}</small>
                          </div>
                      </div>
                      <div class="text-center"><strong>{{coursesFilIds.category }}</strong></div>
                  </div>
              </div>  
          {% endfor %}
    </div>
    <br><hr>
    <!-- This is paginator-->
    <div class="text-end">
      {% if coursesFilId.has_previous %}
          <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page=1">Trang đầu</a>
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.previous_page_number }}">Trang trước</a>-->
      {% endif %}

      {% for i in coursesFilId.paginator.page_range %}
        {% if coursesFilId.number == i %}
          <a class="btn btn-sm btn-outline-primary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
        {% elif i > coursesFilId.number|add:'-10' and i < coursesFilId.number|add:'10' %}
          <a class="btn btn-sm btn-outline-secondary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
        {% endif %}
      {% endfor %}

      {% if coursesFilId.has_next %}
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.next_page_number }}">Tiếp theo</a>-->
          <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesFilId.paginator.num_pages }}">Trang cuối</a>
      {% endif %}
  </div>
  </div>
</div>
{% endblock %}