accounts/urls.py
from django.urls import path, include
from .views import login_view, logout_view,\
    register_view,  password_reset_request


app_name = 'accounts'
urlpatterns = [

    path('accounts/login', login_view, name='login'),
    path('accounts/logout', logout_view, name='logout'),
    path('accounts/register', register_view, name='register'),
    path('accounts/password_reset_request', password_reset_request, name='password_reset'),
]

core/urls.py
from django.urls import path
from .views import IndexClass, About, Contact

app_name = 'core'
urlpatterns = [
    
    path('', IndexClass.as_view(), name='homepage'),
    path('core/about', About.as_view(), name='about'),
    path('core/contact', Contact.as_view(), name='contact'),
]

course_store/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from .admin import admin_site

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('', include('api_rest.urls')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Cấu hình hiển thị images

products/urls.py
from django.urls import path
from .views import detail, detaillesson, typevideo, typecourse

app_name = 'products'
urlpatterns = [
    
    path('detail/<int:courses_id>', detail, name='detail'),
    path('detaillesson/<int:lesson_id>/<int:lessoncourse_id>', detaillesson, name='detaillesson'),
    path('products/typevideo/<int:category_id>', typevideo, name='typevideo'),
    path('products/typecourse/<int:type_id>', typecourse, name='typecourse'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y')
    sex_choice = ((0, 'Male'), (1, 'Female'), (2, 'Orther'))
    sex = models.IntegerField(choices=sex_choice, default=0)
    mobile = models.CharField(default='', max_length=15)
    address = models.CharField(default='', max_length=255)
    zalo = models.CharField(default='', max_length=15)
    social = models.CharField(default='', max_length=255)

core/views.py
from django.shortcuts import render
from products.models import Category, Course
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# *********************Class based view***************************
from django.views.generic import View


# Create your views here.

class IndexClass(View):
    def get(seft, request):
        category = Category.objects.all()  
        course = Course.objects.all().order_by('-id')
        
        page = request.GET.get('page', 1)
        paginator = Paginator(course, 6)
        try:
            course = paginator.page(page)
        except PageNotAnInteger:
            course = paginator.page(1)
        except EmptyPage:
            course = paginator.page(paginator.num_pages)  # Trang cuối

        return render(request, 'core/home.html', {'category': category,
                                                      'course': course,})

class About(View):
    def get(seft, request):        
        category = Category.objects.all()
        return render(request, 'core/about.html', {'category': category,})

class Contact(View):
    def get(seft, request):        
        category = Category.objects.all()
        return render(request, 'core/contact.html', {'category': category,})
    

templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">This is About Us Page</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2021
    </footer>
  </div>

{% endblock %}

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Album Course</title>
    <link rel="stylesheet" href="{% static 'vendor/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'public/css/style_opacity.css' %}">
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">LongMach</a></li>
            <li><a href="#" class="text-white">Long Mạch</a></li>
            <li><a href="#" class="text-white">longmach@gmail.com</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
      
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:contact' %}">Contact</a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                  <a class="nav-link" href="{% url 'accounts:login' %}" >Login</a>
                {% endif %}
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link" href="#">Hello <b>{{user}}</b></a>
                {% else %}
                  <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:password_reset' %}">Reset Password</a>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  REST-GraphQL API
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="api">API ALLs</a></li>
                  <li><a class="dropdown-item" href="apicourses">API Courses</a></li>
                  <li><a class="dropdown-item" href="apilessons">API Lessons</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category List
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'products:typecourse' 1 %}">Special Course</a></li>
                  <li><a class="dropdown-item" href="{% url 'products:typecourse' 0 %}">Free Course</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% for categorys in category %}
                    <li><a class="dropdown-item" href="{% url 'products:typevideo' categorys.id %}">{{ categorys.title }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<!-- Start bootstrap script -->
<script src="{% static 'vendor/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'vendor/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-5.0.2-dist/js/bootstrap.min.js' %}"></script>
<!-- End bootstrap script -->
<script src="{% static 'public/js/script.js' %}"></script>
  </body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">This is Contact Us Page</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2021
    </footer>
  </div>

{% endblock %}

templates/core/home.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for courses in course %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ courses.image.url }}" alt="{{ courses.subject }}" height="225px" />
                        <div class="card-body">
                            <p class="text-center">
                                {% if user.is_authenticated or courses.type == 0 %}
                                    <a href="{% url 'products:detail' courses.id %}">
                                        {{courses.subject }}
                                    </a>
                                {% else %}
                                    {{courses.subject }}
                                {% endif %}
                            </p>
                            <p class="card-text">{{courses.description | safe }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if user.is_authenticated or courses.type == 0 %}
                                    <a href="{% url 'products:detail' courses.id %}" role="button"\
                                     class="btn btn-sm btn-outline-secondary">View</a>
                                    {% else %}
                                    <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Get account</button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Please login view video
                                            </div>
                                            <div class="modal-footer">
                                            <a href="accounts/login" role="button" class="btn btn-primary">I see</a>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                                <small class="text-muted">Star: {{courses.star }}</small>
                            </div>
                        </div>
                        <div class="text-center"><strong>{{courses.category }}</strong></div>
                    </div>
                </div>  
            {% endfor %}
      </div>
      <br><hr>
      <!-- This is paginator-->
      <div class="text-end">
        {% if course.has_previous %}
            <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page=1">Trang đầu</a>
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.previous_page_number }}">Trang trước</a>-->
        {% endif %}

        {% for i in course.paginator.page_range %}
          {% if course.number == i %}
            <a class="btn btn-sm btn-outline-primary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
          {% elif i > course.number|add:'-10' and i < course.number|add:'10' %}
            <a class="btn btn-sm btn-outline-secondary active" href="{{ request.path }}?page={{ i }}">{{ i }}</a>
          {% endif %}
        {% endfor %}

        {% if course.has_next %}
<!--              <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ coursesDetailKey.next_page_number }}">Tiếp theo</a>-->
            <a class="btn btn-sm btn-outline-secondary" href="{{ request.path }}?page={{ course.paginator.num_pages }}">Trang cuối</a>
        {% endif %}
    </div>
    </div>
  </div>
{% endblock %}